### ISSUE TITLE
Error version 0.3.0

### ISSUE THREAD

**Issue by eze92** [Grarak/DSVita#26]
When I open the bubble, after installing the vpk, I get the error C2-12828-1 The main file saved was successful. Uxo: date/ps2-core-1723417593-0x0000182e2-eboot.bin-psp2dmp, with the previous version this did not happen

**Comment by Grarak** [comment]
What was the previous version? 0.2.0?
Also please upload the dump

**Comment by eze92** [comment]
Yes version 0.2.0 and 1 don't have the error. I don't know how do the dump

**Comment by Grarak** [comment]
Just upload the file psp2dump file here

**Comment by Grarak** [comment]
You can use pastebin or upload the file anywhere else

**Comment by Grarak** [comment]
Did you create the ux0:dsvita directory btw? You need to do that

**Comment by Grarak** [comment]
I've pushed a fix
Please try that version https://github.com/Grarak/DSVita/releases/tag/0.3.1

**Comment by eze92** [comment]
Now yes!! I Open the bubble and it's say No rooms found in ux0:data/dsvita , didn't broken , thanks
