### ISSUE TITLE
File-less direct launch for RetroFlow/HexFlow

### ISSUE THREAD

**Issue by BlackSheepBoy69** [Grarak/DSVita#27]
https://github.com/Hydr8gon/NooDS/issues/138

**Comment by Grarak** [comment]
Can you test this?
https://github.com/Grarak/DSVita/actions/runs/10357724238

**Comment by BlackSheepBoy69** [comment]
Wonderful!!!!!!!!!!!!

**Comment by BlackSheepBoy69** [comment]
Here is the LUA+ code I used

    function launch_DSVita(romfile)
	System.executeUri("psgm:play?titleid=DSVITA000" .. "&param=" .. romfile)
	System.exit()
    end

**Comment by BlackSheepBoy69** [comment]
Will probably be added to both RetroFlow and HexFlow Custom in the future like how [flycast-vita](https://github.com/Rinnegatamante/flycast-vita/) was added when it got the upgrade that gave it better compatability. Direct launch works good and thank you for your efforts supporting Vita!

This is the only emulator that runs Pokemon Mystery Dungeon pretty good on it. I like to use NooDS for Brain Age even though NooDS is slow. The sudoku section on Brain Age is probably the best sudoku app ever made but you need to have 'tested your brain age' at least once to access it which takes forever with NooDS so slow

**Comment by Grarak** [comment]
> Will probably be added to both RetroFlow and HexFlow Custom in the future like how [flycast-vita](https://github.com/Rinnegatamante/flycast-vita/) was added when it got the upgrade that gave it better compatability. Direct launch works good and thank you for your efforts supporting Vita!
> 
> DSVita is the only emulator that runs Pokemon Mystery Dungeon pretty good on it. I like to use NooDS (with screen rotation enabled in NooDS settings) for Brain Age even though NooDS is slow. The sudoku section on Brain Age is probably the best sudoku app ever made but you need to have 'tested your brain age' at least once to access it which takes forever with NooDS so slow

Please open a new issue regarding screen rotation. I will take care of that once I am done with optimizations.
