### ISSUE TITLE
Game Compatibilities

### ISSUE THREAD

**Issue by Lumaah** [Grarak/DSVita#34]
i don't know how to put this in Discussions tab so i'll type this here

Super Mario 64 DS (Europe)
Arm7 HLE doesn't work
Game runs at ~30fps but due to poor 3d emulation, you can't get that far in game

WarioWare - Touched! (Europe)
Get stuck at the nintendo screen when Arm7 HLE is activated
Runs at 5 fps when Arm7 HLE is not activated.

Pokemon Dash (USA)
Black screen with and without Arm7 HLE

Rayman DS (USA)
Arm7 HLE doesn't work
Game runs at ~15fps but hangs at the ubisoft presents screen, was able to go into the main menu.

 Mario Kart DS (USA)
 Can't get past the track selection screen using Arm7 HLE
 Game runs at ~15fps but due to poor 3d emulation, it's unplayable
 
 
 Hope this information can help.

**Comment by Grarak** [comment]
Please don't report game compatibility, most games are not playble and it's too much work to moderate these discussions
