### ISSUE TITLE
Actions builds keep crashing

### ISSUE THREAD

**Issue by Rix565** [Grarak/DSVita#36]
When I tried installing some actions/nightly builds, all of them kept crashing when launching any NDS file (game, or even homebrew techdemos) with error code C2-12828-1.

Here is a dump of one of those crashes:

[psp2core-1735388711-0x00001226c7-eboot.bin.psp2dmp.zip](https://github.com/user-attachments/files/18266140/psp2core-1735388711-0x00001226c7-eboot.bin.psp2dmp.zip)

Any idea on how to fix this?

**Comment by Grarak** [comment]
These builds are not meant to be used, please stick to the release builds

**Comment by Rix565** [comment]
They should be able to launch any file at least...

**Comment by Grarak** [comment]
These builds are for me to track down issues.
There is no reason for anyone to use them, unless I specifically say so
